/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#pragma once

#include <jni.h>


namespace jenny {

inline bool initAllProxies(JNIEnv* env) {

   bool success = 
;
   return success;
}

} // end of namespace jenny
